---
- name: Load thunderbolt module at boot
  lineinfile:
    path: /etc/modules
    line: thunderbolt
    state: present
  notify: update initramfs and reboot

- name: Load thunderbolt-net module at boot
  lineinfile:
    path: /etc/modules
    line: thunderbolt-net
    state: present
  notify: update initramfs and reboot

- name: Write systemd-networkd link file for en02
  template:
    src: thunderbolt0.link.j2
    dest: /etc/systemd/network/00-thunderbolt0.link
  notify: update initramfs and reboot

- name: Write systemd-networkd link file for en03
  template:
    src: thunderbolt1.link.j2
    dest: /etc/systemd/network/00-thunderbolt1.link
  notify: update initramfs and reboot

- name: Write /etc/network/interfaces.d/thunderbolt
  copy:
    dest: /etc/network/interfaces.d/thunderbolt
    content: |
      auto en02
      iface en02 inet manual
          mtu 9000

      auto en03
      iface en03 inet manual
          mtu 9000
  notify: update initramfs and reboot

- name: Write udev rules for Thunderbolt interfaces
  copy:
    dest: /etc/udev/rules.d/10-tb-en.rules
    content: |
      ACTION=="move", SUBSYSTEM=="net", KERNEL=="en02", RUN+="/usr/local/bin/pve-en02.sh"
      ACTION=="move", SUBSYSTEM=="net", KERNEL=="en03", RUN+="/usr/local/bin/pve-en03.sh"
  notify: update initramfs and reboot

- name: Install pve-en02.sh helper script
  copy:
    src: pve-en02.sh
    dest: /usr/local/bin/pve-en02.sh
    mode: '0755'

- name: Install pve-en03.sh helper script
  copy:
    src: pve-en03.sh
    dest: /usr/local/bin/pve-en03.sh
    mode: '0755'
