---
- name: Load thunderbolt module at boot
  lineinfile:
    path: /etc/modules
    line: thunderbolt
    state: present
  notify: update initramfs and reboot

- name: Load thunderbolt-net module at boot
  lineinfile:
    path: /etc/modules
    line: thunderbolt-net
    state: present
  notify: update initramfs and reboot

- name: Write systemd-networkd link file for en05
  template:
    src: thunderbolt0.link.j2
    dest: /etc/systemd/network/00-thunderbolt0.link
  notify: update initramfs and reboot

- name: Write systemd-networkd link file for en06
  template:
    src: thunderbolt1.link.j2
    dest: /etc/systemd/network/00-thunderbolt1.link
  notify: update initramfs and reboot

- name: Write /etc/network/interfaces.d/thunderbolt
  copy:
    dest: /etc/network/interfaces.d/thunderbolt
    content: |
      auto en05
      iface en05 inet manual
          mtu 9000

      auto en06
      iface en06 inet manual
          mtu 9000
  notify: update initramfs and reboot

- name: Write udev rules for Thunderbolt interfaces
  copy:
    dest: /etc/udev/rules.d/10-tb-en.rules
    content: |
      ACTION=="move", SUBSYSTEM=="net", KERNEL=="en05", RUN+="/usr/local/bin/pve-en05.sh"
      ACTION=="move", SUBSYSTEM=="net", KERNEL=="en06", RUN+="/usr/local/bin/pve-en06.sh"
  notify: update initramfs and reboot

- name: Install pve-en05.sh helper script
  copy:
    src: pve-en05.sh
    dest: /usr/local/bin/pve-en05.sh
    mode: '0755'

- name: Install pve-en06.sh helper script
  copy:
    src: pve-en06.sh
    dest: /usr/local/bin/pve-en06.sh
    mode: '0755'
